apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-personal-team
  namespace: ai-personal-team
  labels:
    app: ai-personal-team
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-personal-team
      component: frontend
  template:
    metadata:
      labels:
        app: ai-personal-team
        component: frontend
    spec:
      containers:
      - name: ai-personal-team
        image: ai-personal-team:v2.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        # Add environment variables for API keys (these would come from Kubernetes secrets in production)
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-personal-team-secrets
              key: openai-api-key
              optional: true
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-personal-team-secrets
              key: supabase-url
              optional: true
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: ai-personal-team-secrets
              key: supabase-anon-key
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-personal-team-service
  namespace: ai-personal-team
  labels:
    app: ai-personal-team
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ai-personal-team
    component: frontend
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-personal-team-secrets
  namespace: ai-personal-team
type: Opaque
data:
  # These are base64 encoded placeholder values
  # In production, you would use real API keys
  openai-api-key: cGxhY2Vob2xkZXI=  # placeholder
  supabase-url: cGxhY2Vob2xkZXI=    # placeholder
  supabase-anon-key: cGxhY2Vob2xkZXI= # placeholder
